### ISSUE TITLE
Using Developer Account 

### ISSUE THREAD

**Issue by jhamzo** [SignTools/ios-signer-ci#6]
when I use developer account it get stuck at 90. ./sign.sh - Logging in 1/2 
and I didn't get the 2FA code . 

I'm using semaphoreci

**Comment by ViRb3** [comment]
Hello. SemaphoreCI does not support developer accounts, only manual provisioning profiles. This is because they lack the automation permission that is necessary to perform the login. Only GitHub can be used at this time.
