### ISSUE TITLE
ApplicationVerificationFailed

### ISSUE THREAD

**Issue by lasercow5** [SignTools/ios-signer-ci#8]
My apps get singed successfully, but when trying to install I get "This app cannot be installed because its integrity could not be verified.".

Using ideviceinstaller, the error is "ApplicationVerificationFailed" with code 0xe8008016 "The executable was signed with invalid entitlements."

My device is added to my developer account

**Comment by ViRb3** [comment]
Please ensure everything is updated, and if you still have issues, check: https://github.com/SignTools/ios-signer-service/blob/master/FAQ.md#this-app-cannot-be-installed-because-its-integrity-could-not-be-verified. Please open an issue in that repo, not here.
